- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Update apt packages
    apt:
      update_cache: yes
      force_apt_get: yes
  - name: Add Dockers official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  - name: Add apt-key from google cloud
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
  - name: Update apt packages again
    apt:
      update_cache: yes
      force_apt_get: yes
  - name: Install wanted packages
    apt:
      name:
        - docker.io
        - kubectl
        - kubeadm
        - kubelet
  - name: Init Net bridge
    shell: echo "net.bridge.bridge-nf-call-iptables=1" | tee -a /etc/sysctl.conf && sysctl -p


- hosts: K8Smaster
  become: true
  become_user: root
  tasks:
  - name: kubeadm init network CIDR
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  - name: init K8S config file
    shell: mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config
  - name: Apply flannel CNI
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  - name: copy pwd content to variable
    shell: pwd
    register: x

  - debug:
     msg: "{{ x }}"
